### ISSUE TITLE
Cuidado com operadores de comparação em PHP

### ISSUE THREAD

**Issue by galmirpr** [arthurmeira/PHP_Funcao_ImparPar#1]
Na parte que se refere a:
` if($impar = $numero % 2){`
O sinal de = é um sinal de alteração e não equivalência.
O que ocorre realmente é que `$impar` recebe `$numero % 2` (_true_ ou _false_).
O PHP é flexível suficiente para permitir essas coisas, 
ele analisará o valor de `$impar` como booleano e dirá se é _true_ ou _false_.

**Tome cuidado pois isso pode causar problemas futuros imprevisíveis.**
Use apropriadamente os [operadores de comparação](https://www.php.net/manual/pt_BR/language.operators.comparison.php).
Nesse caso, o `$impar` é desnecessário, uma vez que `$numero % 2` já é uma expressão que retorna **verdadeiro** ou **falso**.

Outra o sinal de % é sinal de módulo, ele pega o resto da divisão, isso significa que um número par é um número com resto igual a 0, e impar qualquer outro valor. Ou seja: `if ($numero % 2 === 0)` ou analisar o impar através de `if ($numero % 2 !== 0).` ou `if ($numero % 2)`

Bons estudos. 😊

**Comment by arthurmeira** [comment]
Obrigado pelo alerta, vou corrigir


Gabriel Almir ***@***.***> escreveu no dia sexta, 4/03/2022
à(s) 17:15:
